import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ModalProvider } from "@/components/GlobalModal";
import "./globals.css";

import Providers from "@/utils/Providers";
import { Toaster } from "react-hot-toast";

// import AnimatedLayout from "@/components/AnimatedLayout";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body lang="en" className={`${geist.variable} ${geistMono.variable} antialiased`}>
        <main className="bg-bluelayer min-h-screen">
          {/* <AnimatedLayout> */}
          <Providers>
            <ModalProvider>{children} <Toaster position="top-right" /> </ModalProvider>
          </Providers>
          {/* </AnimatedLayout> */}
        </main>
      </body>
    </html>
  );
}
