import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { ModalProvider } from "@/components/GlobalModal";
import "./globals.css";
// import AnimatedLayout from "@/components/AnimatedLayout";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
  variable: "--font-work-sans", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${workSans.variable} antialiased`}>
        <main className="bg-bluelayer min-h-screen">
          {/* <AnimatedLayout> */}
          <ModalProvider>{children} </ModalProvider>
          {/* </AnimatedLayout> */}
        </main>
      </body>
    </html>
  );
}
