export const PRIVACY_SECTIONS = [
  { id: "about", title: "About this notice" },
  { id: "information-we-collect", title: "1. What information do we collect?" },
  { id: "how-we-process", title: "2. How do we process your information?" },
  { id: "legal-bases", title: "3. What legal bases do we rely on?" },
  { id: "sharing", title: "4. When and with whom do we share your personal information?" },
  { id: "cookies", title: "5. Do we use cookies and other tracking technologies?" },
  { id: "ai-products", title: "6. Do we offer artificial intelligence-based products?" },
  { id: "social-logins", title: "7. How do we handle your social logins?" },
  { id: "retention", title: "8. How long do we keep your information?" },
  { id: "security", title: "9. How do we keep your information safe?" },
  { id: "minors", title: "10. Do we collect information from minors?" },
  { id: "privacy-rights", title: "11. What are your privacy rights?" },
  { id: "dnt", title: "12. Controls for Do-Not-Track features" },
  { id: "us-residents", title: "13. Do United States residents have specific privacy rights?" },
  { id: "platform-ip", title: "14. Platform data & intellectual property" },
  { id: "updates", title: "15. Do we make updates to this notice?" },
  { id: "contact", title: "16. How can you contact us about this notice?" },
  { id: "review-data", title: "17. How can you review, update, or delete the data we collect from you?" },
  { id: "platform-terms", title: "18. Platform-specific terms & compliance" },
  { id: "addendum", title: "Compliance addendum" },
] as const;
